// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#include "packet.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace PacketLib {

inline constexpr UG_ECHO_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : echo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UG_ECHO_REQ::UG_ECHO_REQ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UG_ECHO_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UG_ECHO_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UG_ECHO_REQDefaultTypeInternal() {}
  union {
    UG_ECHO_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UG_ECHO_REQDefaultTypeInternal _UG_ECHO_REQ_default_instance_;

inline constexpr GU_ECHO_RES::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : echo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GU_ECHO_RES::GU_ECHO_RES(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GU_ECHO_RESDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GU_ECHO_RESDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GU_ECHO_RESDefaultTypeInternal() {}
  union {
    GU_ECHO_RES _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GU_ECHO_RESDefaultTypeInternal _GU_ECHO_RES_default_instance_;
}  // namespace PacketLib
static ::_pb::Metadata file_level_metadata_packet_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_packet_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_packet_2eproto = nullptr;
const ::uint32_t TableStruct_packet_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PacketLib::UG_ECHO_REQ, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PacketLib::UG_ECHO_REQ, _impl_.echo_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PacketLib::GU_ECHO_RES, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PacketLib::GU_ECHO_RES, _impl_.echo_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::PacketLib::UG_ECHO_REQ)},
        {9, -1, -1, sizeof(::PacketLib::GU_ECHO_RES)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::PacketLib::_UG_ECHO_REQ_default_instance_._instance,
    &::PacketLib::_GU_ECHO_RES_default_instance_._instance,
};
const char descriptor_table_protodef_packet_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014packet.proto\022\tPacketLib\"\033\n\013UG_ECHO_REQ"
    "\022\014\n\004echo\030\001 \001(\t\"\033\n\013GU_ECHO_RES\022\014\n\004echo\030\001 "
    "\001(\t*U\n\tPACKET_ID\022\022\n\016PACKET_ID_NONE\020\000\022\031\n\025"
    "PACKET_ID_UG_ECHO_REQ\020\001\022\031\n\025PACKET_ID_GU_"
    "ECHO_RES\020eb\006proto3"
};
static ::absl::once_flag descriptor_table_packet_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_packet_2eproto = {
    false,
    false,
    178,
    descriptor_table_protodef_packet_2eproto,
    "packet.proto",
    &descriptor_table_packet_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_packet_2eproto::offsets,
    file_level_metadata_packet_2eproto,
    file_level_enum_descriptors_packet_2eproto,
    file_level_service_descriptors_packet_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_packet_2eproto_getter() {
  return &descriptor_table_packet_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_packet_2eproto(&descriptor_table_packet_2eproto);
namespace PacketLib {
const ::google::protobuf::EnumDescriptor* PACKET_ID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_packet_2eproto);
  return file_level_enum_descriptors_packet_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PACKET_ID_internal_data_[] = {
    131072u, 65536u, 101u, };
bool PACKET_ID_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, PACKET_ID_internal_data_);
}
// ===================================================================

class UG_ECHO_REQ::_Internal {
 public:
};

UG_ECHO_REQ::UG_ECHO_REQ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PacketLib.UG_ECHO_REQ)
}
inline PROTOBUF_NDEBUG_INLINE UG_ECHO_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : echo_(arena, from.echo_),
        _cached_size_{0} {}

UG_ECHO_REQ::UG_ECHO_REQ(
    ::google::protobuf::Arena* arena,
    const UG_ECHO_REQ& from)
    : ::google::protobuf::Message(arena) {
  UG_ECHO_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:PacketLib.UG_ECHO_REQ)
}
inline PROTOBUF_NDEBUG_INLINE UG_ECHO_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : echo_(arena),
        _cached_size_{0} {}

inline void UG_ECHO_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UG_ECHO_REQ::~UG_ECHO_REQ() {
  // @@protoc_insertion_point(destructor:PacketLib.UG_ECHO_REQ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UG_ECHO_REQ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.echo_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UG_ECHO_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:PacketLib.UG_ECHO_REQ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.echo_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UG_ECHO_REQ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> UG_ECHO_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UG_ECHO_REQ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string echo = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UG_ECHO_REQ, _impl_.echo_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string echo = 1;
    {PROTOBUF_FIELD_OFFSET(UG_ECHO_REQ, _impl_.echo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\0\0\0\0\0\0"
    "PacketLib.UG_ECHO_REQ"
    "echo"
  }},
};

::uint8_t* UG_ECHO_REQ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PacketLib.UG_ECHO_REQ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string echo = 1;
  if (!this->_internal_echo().empty()) {
    const std::string& _s = this->_internal_echo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PacketLib.UG_ECHO_REQ.echo");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PacketLib.UG_ECHO_REQ)
  return target;
}

::size_t UG_ECHO_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PacketLib.UG_ECHO_REQ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string echo = 1;
  if (!this->_internal_echo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_echo());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UG_ECHO_REQ::_class_data_ = {
    UG_ECHO_REQ::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UG_ECHO_REQ::GetClassData() const {
  return &_class_data_;
}

void UG_ECHO_REQ::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UG_ECHO_REQ*>(&to_msg);
  auto& from = static_cast<const UG_ECHO_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PacketLib.UG_ECHO_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_echo().empty()) {
    _this->_internal_set_echo(from._internal_echo());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UG_ECHO_REQ::CopyFrom(const UG_ECHO_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacketLib.UG_ECHO_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UG_ECHO_REQ::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UG_ECHO_REQ::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UG_ECHO_REQ::InternalSwap(UG_ECHO_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.echo_, &other->_impl_.echo_, arena);
}

::google::protobuf::Metadata UG_ECHO_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_packet_2eproto_getter, &descriptor_table_packet_2eproto_once,
      file_level_metadata_packet_2eproto[0]);
}
// ===================================================================

class GU_ECHO_RES::_Internal {
 public:
};

GU_ECHO_RES::GU_ECHO_RES(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PacketLib.GU_ECHO_RES)
}
inline PROTOBUF_NDEBUG_INLINE GU_ECHO_RES::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : echo_(arena, from.echo_),
        _cached_size_{0} {}

GU_ECHO_RES::GU_ECHO_RES(
    ::google::protobuf::Arena* arena,
    const GU_ECHO_RES& from)
    : ::google::protobuf::Message(arena) {
  GU_ECHO_RES* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:PacketLib.GU_ECHO_RES)
}
inline PROTOBUF_NDEBUG_INLINE GU_ECHO_RES::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : echo_(arena),
        _cached_size_{0} {}

inline void GU_ECHO_RES::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GU_ECHO_RES::~GU_ECHO_RES() {
  // @@protoc_insertion_point(destructor:PacketLib.GU_ECHO_RES)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GU_ECHO_RES::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.echo_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GU_ECHO_RES::Clear() {
// @@protoc_insertion_point(message_clear_start:PacketLib.GU_ECHO_RES)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.echo_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GU_ECHO_RES::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> GU_ECHO_RES::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GU_ECHO_RES_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string echo = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GU_ECHO_RES, _impl_.echo_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string echo = 1;
    {PROTOBUF_FIELD_OFFSET(GU_ECHO_RES, _impl_.echo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\4\0\0\0\0\0\0"
    "PacketLib.GU_ECHO_RES"
    "echo"
  }},
};

::uint8_t* GU_ECHO_RES::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PacketLib.GU_ECHO_RES)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string echo = 1;
  if (!this->_internal_echo().empty()) {
    const std::string& _s = this->_internal_echo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PacketLib.GU_ECHO_RES.echo");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PacketLib.GU_ECHO_RES)
  return target;
}

::size_t GU_ECHO_RES::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PacketLib.GU_ECHO_RES)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string echo = 1;
  if (!this->_internal_echo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_echo());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GU_ECHO_RES::_class_data_ = {
    GU_ECHO_RES::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GU_ECHO_RES::GetClassData() const {
  return &_class_data_;
}

void GU_ECHO_RES::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GU_ECHO_RES*>(&to_msg);
  auto& from = static_cast<const GU_ECHO_RES&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PacketLib.GU_ECHO_RES)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_echo().empty()) {
    _this->_internal_set_echo(from._internal_echo());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GU_ECHO_RES::CopyFrom(const GU_ECHO_RES& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacketLib.GU_ECHO_RES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GU_ECHO_RES::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GU_ECHO_RES::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GU_ECHO_RES::InternalSwap(GU_ECHO_RES* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.echo_, &other->_impl_.echo_, arena);
}

::google::protobuf::Metadata GU_ECHO_RES::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_packet_2eproto_getter, &descriptor_table_packet_2eproto_once,
      file_level_metadata_packet_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace PacketLib
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
