# 베이스 이미지
FROM ubuntu:22.04

# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    ninja-build \
    g++ \
    make \
    curl \
    zip \
    unzip \
    tar \
    libssl-dev \
    bzip2 \
    pkg-config \
    autoconf \
    automake \
    autoconf-archive \
    autotools-dev \
    libtool \
    python3-dev \
    python3-setuptools \
    python3-distutils \
    && rm -rf /var/lib/apt/lists/*

# vcpkg 설치
WORKDIR /vcpkg
RUN git clone https://github.com/microsoft/vcpkg.git . && \
    ./bootstrap-vcpkg.sh

# vcpkg 환경 변수 설정
ENV VCPKG_ROOT=/vcpkg
ENV PATH="$VCPKG_ROOT:$PATH"

# JunCore 프로젝트 복제
WORKDIR /app
RUN git clone https://github.com/dkdldjswkd/JunCore .

# 의존성 설치
WORKDIR /app/JunCore
RUN vcpkg install

# cmake 빌드
RUN cmake --preset x64-release-linux && \
    cmake --build --preset x64-release-linux .

# 빌드 후 실행 디렉토리로 이동
WORKDIR /app/JunCore/out/build/x64-release-linux/src/echo_server

# 실행 파일 실행
ENTRYPOINT ["./echo_server"]