# 베이스 이미지
FROM ubuntu:22.04

# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    g++ \
    make \
    curl \
    zip \
    unzip \
    tar \
    libssl-dev \
    bzip2 \
    pkg-config \
    autoconf \
    automake \
    autoconf-archive \
    autotools-dev \
    libtool \
    python3-dev \
    python3-setuptools \
    python3-distutils \
    && rm -rf /var/lib/apt/lists/*
	
# vcpkg 설치
WORKDIR /vcpkg
RUN git clone https://github.com/microsoft/vcpkg.git . && \
    ./bootstrap-vcpkg.sh

# vcpkg 환경 변수 설정
ENV VCPKG_ROOT=/vcpkg
ENV PATH="$VCPKG_ROOT:$PATH"

# 필요한 라이브러리 설치 (Boost 및 Protobuf)
RUN vcpkg install boost:x64-linux && \
    vcpkg install protobuf:x64-linux

# JunCore 프로젝트 복제
WORKDIR /app
RUN git clone https://github.com/dkdldjswkd/JunCore .

# # CMake 빌드 설정
# WORKDIR /app/JunCore
# RUN cmake -B build -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake && \
#    cmake --build build
	
# # 빌드된 실행 파일 복사
# COPY --from=builder /app/JunCore/build/JunCore /app/JunCore

# 실행 디렉토리로 이동
# WORKDIR /app/JunCore

# 실행 파일 실행
# ENTRYPOINT ["./JunCore"]